name: first-test-action

on: [push, fork]

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: print
            run: echo "test data to display on the console"
        
          - name: list 
            run: ls


